- project:
    templates:
      - publish-tox-docs-infra
    check:
      jobs: &jobs
        - tox-linters
        - tox-py35:
            nodeset: ubuntu-xenial
        - tox-py36
        - tox-py37
        - tox-py38
        - tox-py39:
            nodeset: ubuntu-focal
    gate:
      jobs: *jobs
