- project:
    templates:
      - openstack-python35-jobs-no-constraints
      - publish-tox-docs-infra
    check:
      jobs:
        - tox-linters
        - tox-py36
    gate:
      jobs:
        - tox-linters
        - tox-py36
